B4A=true
Group=Default Group
ModulesStructureVersion=1
Type=StaticCode
Version=13
@EndOfDesignText@
' Help texts, maintained by hand. Keep in sync with web/src/catalog.ts and docs/quantity_catalog.json.
' tools/generate_latex_assets.js renders the Equation entries into Files/katex/eq.
Sub Process_Globals
End Sub
Public Sub Help(Key As String) As String
    Select Key
    Case "Hp"
        Return "Pressure altitude / H_P" & CRLF & CRLF & "Definition: ISA altitude corresponding to the local static pressure. Positive: pressure below ISA sea-level pressure." & CRLF & CRLF & "Equation: p_{\mathrm{ISA}}(H_P) = p" & CRLF & CRLF & "SI/reference unit: m"
    Case "Hg"
        Return "Geometric altitude / h" & CRLF & CRLF & "Definition: Geometric height above mean sea level. Positive: above mean sea level." & CRLF & CRLF & "Equation: h = \frac{r_0 \, H}{r_0 - H}" & CRLF & CRLF & "SI/reference unit: m"
    Case "P"
        Return "Static pressure / p" & CRLF & CRLF & "Definition: Absolute static pressure of the surrounding air, related to density and absolute temperature by the ideal gas law." & CRLF & CRLF & "Equation: p = \rho \, R \, T" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Δ ISA"
        Return "ISA temperature deviation / ΔT" & CRLF & CRLF & "Definition: Difference between actual static air temperature and ISA temperature at the same pressure altitude. Positive: warmer than ISA." & CRLF & CRLF & "Equation: \Delta T = T - T_{\mathrm{ISA}}(H_P)" & CRLF & CRLF & "SI/reference unit: K"
    Case "OAT"
        Return "Outside air temperature / OAT" & CRLF & CRLF & "Definition: Static temperature of the surrounding air." & CRLF & CRLF & "Equation: T = T_{\mathrm{ISA}}(H_P) + \Delta T" & CRLF & CRLF & "SI/reference unit: K"
    Case "TAS"
        Return "True airspeed / TAS" & CRLF & CRLF & "Definition: Magnitude of aircraft velocity relative to the surrounding air. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{TAS} = M \cdot a" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "CAS"
        Return "Calibrated airspeed / CAS" & CRLF & CRLF & "Definition: Airspeed at ISA sea-level conditions producing the same impact pressure as the actual flight condition. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{CAS} = a_0 \sqrt{\frac{2}{\gamma - 1} \left[ \left( \frac{q_c}{p_0} + 1 \right)^{\frac{\gamma - 1}{\gamma}} - 1 \right]}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "EAS"
        Return "Equivalent airspeed / EAS" & CRLF & CRLF & "Definition: Airspeed at ISA sea-level conditions producing the same dynamic pressure as the actual flight condition. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{EAS} = \mathrm{TAS} \sqrt{\frac{\rho}{\rho_0}}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Mach"
        Return "Mach number / M" & CRLF & CRLF & "Definition: Ratio of true airspeed to local speed of sound. Nonnegative." & CRLF & CRLF & "Equation: M = \frac{\mathrm{TAS}}{a}" & CRLF & CRLF & "SI/reference unit: —"
    Case "CL"
        Return "Lift coefficient / C_L" & CRLF & CRLF & "Definition: Aerodynamic lift divided by the product of dynamic pressure and wing reference area. Positive: lift toward the aircraft upper side." & CRLF & CRLF & "Equation: C_L = \frac{n \cdot m \cdot g_0}{q \cdot S_{\mathrm{REF}}}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Vs Factor Output"
        Return "Stall speed factor / V_S factor" & CRLF & CRLF & "Definition: Ratio of current calibrated airspeed to reference 1-g stall speed in CAS. Nonnegative." & CRLF & CRLF & "SI/reference unit: —"
    Case "Vs Factor"
        Return "Stall speed factor / V_S factor" & CRLF & CRLF & "Definition: Input multiplier applied to reference 1-g stall speed in CAS, with an optional additive CAS increment. Nonnegative multiplier." & CRLF & CRLF & "Equation: \mathrm{CAS} = \mathrm{factor} \times V_{S,\mathrm{CAS}} + \Delta \mathrm{CAS}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Ground Speed"
        Return "Ground speed / GS" & CRLF & CRLF & "Definition: Magnitude of aircraft horizontal velocity relative to the ground. Nonnegative." & CRLF & CRLF & "Equation: V_{\mathrm{ground}} = V_{\mathrm{air}} + V_{\mathrm{wind}}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Qdyn"
        Return "Dynamic pressure / q" & CRLF & CRLF & "Definition: Kinetic energy per unit volume of the air-relative flow. Nonnegative." & CRLF & CRLF & "Equation: q = \frac{1}{2} \rho \, \mathrm{TAS}^2" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Qc"
        Return "Impact pressure / q_c" & CRLF & CRLF & "Definition: Difference between stagnation pressure and static pressure. Nonnegative in the adopted subsonic model." & CRLF & CRLF & "Equation: q_c = p \left[ \left( 1 + \frac{\gamma - 1}{2} M^2 \right)^{\frac{\gamma}{\gamma - 1}} - 1 \right]" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Weight"
        Return "Aircraft mass / m" & CRLF & CRLF & "Definition: Aircraft weight, expressed as mass in the selected units for aerodynamic calculations. Nonnegative." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "Sref"
        Return "Wing reference area / S_{REF}" & CRLF & CRLF & "Definition: Wing reference area used to define aerodynamic coefficients. Positive area." & CRLF & CRLF & "Equation: L = q \, S_{\mathrm{REF}} \, C_L" & CRLF & CRLF & "SI/reference unit: m²"
    Case "cref"
        Return "Reference chord / c_{REF}" & CRLF & CRLF & "Definition: Wing reference chord used to calculate Reynolds number. Positive length." & CRLF & CRLF & "Equation: \mathrm{Re} = \frac{\rho \, \mathrm{TAS} \, c_{\mathrm{REF}}}{\mu}" & CRLF & CRLF & "SI/reference unit: m"
    Case "CLmax"
        Return "Maximum lift coefficient / C_{L,MAX}" & CRLF & CRLF & "Definition: Maximum lift coefficient attainable at the onset of stall for the selected aircraft configuration. Positive coefficient." & CRLF & CRLF & "Equation: V_{S,\mathrm{TAS}} = \sqrt{\frac{2 \, m \, g_0}{\rho \, S_{\mathrm{REF}} \, C_{L,\mathrm{MAX}}}}" & CRLF & CRLF & "SI/reference unit: —"
    Case "NzPullup"
        Return "Pull-up load factor / N_Z" & CRLF & CRLF & "Definition: Ratio of aerodynamic lift to aircraft weight in an unbanked maneuver. Positive: lift toward the aircraft upper side." & CRLF & CRLF & "Equation: L = n \cdot m \cdot g_0" & CRLF & CRLF & "SI/reference unit: g"
    Case "NzTurn"
        Return "Level turn load factor / N_Z" & CRLF & CRLF & "Definition: Load factor in a coordinated level turn. Positive and not less than 1 in the adopted model." & CRLF & CRLF & "Equation: n = \frac{1}{\cos \varphi}" & CRLF & CRLF & "SI/reference unit: g"
    Case "BankTurn"
        Return "Level turn bank angle / φ" & CRLF & CRLF & "Definition: Aircraft bank angle in a coordinated level turn. Positive: right wing down." & CRLF & CRLF & "Equation: n = \frac{1}{\cos \varphi}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Track"
        Return "Ground track angle / χ" & CRLF & CRLF & "Definition: Direction of the aircraft horizontal ground-velocity vector, measured clockwise from true north. Positive: clockwise (ground-velocity vector to the right)." & CRLF & CRLF & "Equation: \vec{V}_{\mathrm{ground}} = \vec{V}_{\mathrm{air}} + \vec{V}_{\mathrm{wind}}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Heading"
        Return "Aircraft heading / ψ" & CRLF & CRLF & "Definition: Direction in which the aircraft nose points, measured clockwise from true north. Positive: clockwise (nose to the right)." & CRLF & CRLF & "Equation: \psi = \chi + \mathrm{drift}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Sideslip"
        Return "Sideslip angle / β" & CRLF & CRLF & "Definition: Angle between the aircraft longitudinal axis and the incoming relative wind. Positive: relative wind coming from the right." & CRLF & CRLF & "Equation: \beta = \angle\left(\psi,\ \vec{V}_{\mathrm{air}}\right)" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Drift"
        Return "Drift angle / drift" & CRLF & CRLF & "Definition: Angular difference between heading and ground track (heading minus track). Positive: heading to the right of track." & CRLF & CRLF & "Equation: \mathrm{drift} = \psi - \chi" & CRLF & CRLF & "SI/reference unit: rad"
    Case "HeadWind"
        Return "Reference headwind / HW" & CRLF & CRLF & "Definition: Wind component along the selected runway/reference direction. Positive: wind from ahead. Negative: tailwind." & CRLF & CRLF & "Equation: \mathrm{HW} = V_W \cos(\psi_W - \psi_{\mathrm{RWY}})" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Wind Speed"
        Return "Wind speed / V_W" & CRLF & CRLF & "Definition: Magnitude of horizontal wind velocity. Nonnegative." & CRLF & CRLF & "Equation: V_W = \sqrt{\mathrm{HW}^2 + \mathrm{CW}^2}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "CrossWind"
        Return "Reference crosswind / CW" & CRLF & CRLF & "Definition: Wind component perpendicular to the selected runway/reference direction. Positive: wind coming from the right. Negative: wind from the left." & CRLF & CRLF & "Equation: \mathrm{CW} = V_W \sin(\psi_W - \psi_{\mathrm{RWY}})" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Runway Angle"
        Return "Runway reference angle / RWY" & CRLF & CRLF & "Definition: Direction of the selected runway/reference axis, measured clockwise from true north. Positive: clockwise (reference direction to the right)." & CRLF & CRLF & "Equation: \psi_{\mathrm{RWY}} = \text{runway heading}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Wind Direction"
        Return "Wind direction from / wind from" & CRLF & CRLF & "Definition: Direction from which the wind blows, measured clockwise from true north. Positive: clockwise (wind-from direction to the right)." & CRLF & CRLF & "Equation: \psi_W = \text{meteorological wind direction}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Pressure Altitude"
        Return "Pressure altitude / H_P" & CRLF & CRLF & "Definition: ISA altitude corresponding to the local static pressure. Positive: pressure below ISA sea-level pressure." & CRLF & CRLF & "Equation: p_{\mathrm{ISA}}(H_P) = p" & CRLF & CRLF & "SI/reference unit: m"
    Case "Geometric Altitude"
        Return "Geometric altitude / h" & CRLF & CRLF & "Definition: Geometric height above mean sea level. Positive: above mean sea level." & CRLF & CRLF & "Equation: h = \frac{r_0 \, H}{r_0 - H}" & CRLF & CRLF & "SI/reference unit: m"
    Case "Pressure"
        Return "Static pressure / p" & CRLF & CRLF & "Definition: Absolute static pressure of the surrounding air, related to density and absolute temperature by the ideal gas law." & CRLF & CRLF & "Equation: p = \rho \, R \, T" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Temperature"
        Return "Outside air temperature / OAT" & CRLF & CRLF & "Definition: Static temperature of the surrounding air." & CRLF & CRLF & "Equation: T = T_{\mathrm{ISA}}(H_P) + \Delta T" & CRLF & CRLF & "SI/reference unit: K"
    Case "Delta ISA"
        Return "ISA temperature deviation / ΔT" & CRLF & CRLF & "Definition: Difference between actual static air temperature and ISA temperature at the same pressure altitude. Positive: warmer than ISA." & CRLF & CRLF & "Equation: \Delta T = T - T_{\mathrm{ISA}}(H_P)" & CRLF & CRLF & "SI/reference unit: K"
    Case "True Airspeed"
        Return "True airspeed / TAS" & CRLF & CRLF & "Definition: Magnitude of aircraft velocity relative to the surrounding air. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{TAS} = M \cdot a" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Calibrated Airspeed"
        Return "Calibrated airspeed / CAS" & CRLF & CRLF & "Definition: Airspeed at ISA sea-level conditions producing the same impact pressure as the actual flight condition. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{CAS} = a_0 \sqrt{\frac{2}{\gamma - 1} \left[ \left( \frac{q_c}{p_0} + 1 \right)^{\frac{\gamma - 1}{\gamma}} - 1 \right]}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Equivalent Airspeed"
        Return "Equivalent airspeed / EAS" & CRLF & CRLF & "Definition: Airspeed at ISA sea-level conditions producing the same dynamic pressure as the actual flight condition. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{EAS} = \mathrm{TAS} \sqrt{\frac{\rho}{\rho_0}}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Lift Coefficient CL"
        Return "Lift coefficient / C_L" & CRLF & CRLF & "Definition: Aerodynamic lift divided by the product of dynamic pressure and wing reference area. Positive: lift toward the aircraft upper side." & CRLF & CRLF & "Equation: C_L = \frac{n \cdot m \cdot g_0}{q \cdot S_{\mathrm{REF}}}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Dynamic Pressure"
        Return "Dynamic pressure / q" & CRLF & CRLF & "Definition: Kinetic energy per unit volume of the air-relative flow. Nonnegative." & CRLF & CRLF & "Equation: q = \frac{1}{2} \rho \, \mathrm{TAS}^2" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Impact Pressure"
        Return "Impact pressure / q_c" & CRLF & CRLF & "Definition: Difference between stagnation pressure and static pressure. Nonnegative in the adopted subsonic model." & CRLF & CRLF & "Equation: q_c = p \left[ \left( 1 + \frac{\gamma - 1}{2} M^2 \right)^{\frac{\gamma}{\gamma - 1}} - 1 \right]" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "Bank Angle φ"
        Return "Level turn bank angle / φ" & CRLF & CRLF & "Definition: Aircraft bank angle in a coordinated level turn. Positive: right wing down." & CRLF & CRLF & "Equation: n = \frac{1}{\cos \varphi}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Track Angle"
        Return "Ground track angle / χ" & CRLF & CRLF & "Definition: Direction of the aircraft horizontal ground-velocity vector, measured clockwise from true north. Positive: clockwise (ground-velocity vector to the right)." & CRLF & CRLF & "Equation: \vec{V}_{\mathrm{ground}} = \vec{V}_{\mathrm{air}} + \vec{V}_{\mathrm{wind}}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Heading Angle Ψ"
        Return "Aircraft heading / ψ" & CRLF & CRLF & "Definition: Direction in which the aircraft nose points, measured clockwise from true north. Positive: clockwise (nose to the right)." & CRLF & CRLF & "Equation: \psi = \chi + \mathrm{drift}" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Drift Angle"
        Return "Drift angle / drift" & CRLF & CRLF & "Definition: Angular difference between heading and ground track (heading minus track). Positive: heading to the right of track." & CRLF & CRLF & "Equation: \mathrm{drift} = \psi - \chi" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Sideslip Angle β"
        Return "Sideslip angle / β" & CRLF & CRLF & "Definition: Angle between the aircraft longitudinal axis and the incoming relative wind. Positive: relative wind coming from the right." & CRLF & CRLF & "Equation: \beta = \angle\left(\psi,\ \vec{V}_{\mathrm{air}}\right)" & CRLF & CRLF & "SI/reference unit: rad"
    Case "Geopotential Altitude"
    ' H_G below is renderer markup: FormatScriptedText displays g as a subscript; the underscore is never shown.
        Return "Geopotential altitude / H_G" & CRLF & CRLF & "Definition: Altitude equivalent to gravitational potential energy per unit mass under constant standard gravity. Positive: above the reference datum." & CRLF & CRLF & "Equation: H = \frac{r_0 \, h}{r_0 + h}" & CRLF & CRLF & "SI/reference unit: m"
    Case "Density Altitude"
        Return "Density altitude / H_ρ" & CRLF & CRLF & "Definition: ISA altitude corresponding to the actual air density. Positive: above ISA sea level." & CRLF & CRLF & "Equation: \rho_{\mathrm{ISA}}(H_\rho) = \rho" & CRLF & CRLF & "SI/reference unit: m"
    Case "Temperature Altitude"
        Return "Temperature altitude / H_T" & CRLF & CRLF & "Definition: Tropospheric ISA altitude corresponding to actual static temperature, limited to 11 km in this model. Positive: above ISA sea level." & CRLF & CRLF & "Equation: T_{\mathrm{ISA}}(H_T) = T" & CRLF & CRLF & "SI/reference unit: m"
    Case "Density"
        Return "Air density / ρ" & CRLF & CRLF & "Definition: Mass of air per unit volume, calculated from static pressure and absolute temperature using the ideal gas law. Positive scalar." & CRLF & CRLF & "Equation: \rho = \frac{p}{R \, T}" & CRLF & CRLF & "SI/reference unit: kg/m³"
    Case "Total Temperature"
        Return "Total air temperature / TAT" & CRLF & CRLF & "Definition: Stagnation temperature obtained by adiabatically bringing the air-relative flow to rest." & CRLF & CRLF & "Equation: T_T = T \left( 1 + \frac{\gamma - 1}{2} M^2 \right)" & CRLF & CRLF & "SI/reference unit: K"
    Case "Viscosity"
        Return "Dynamic viscosity / μ" & CRLF & CRLF & "Definition: Dynamic viscosity of air relates shear stress to velocity gradient; its temperature dependence is modeled by Sutherland's law. Positive scalar." & CRLF & CRLF & "Equation: \mu = \mu_0 \, \frac{T_0 + C}{T + C} \left( \frac{T}{T_0} \right)^{3/2}" & CRLF & CRLF & "SI/reference unit: Pa·s"
    Case "Sound Speed"
        Return "Speed of sound / a" & CRLF & CRLF & "Definition: Speed of propagation of small pressure disturbances in the surrounding air. Positive scalar." & CRLF & CRLF & "Equation: a = \sqrt{\gamma \, R \, T}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Stall Speed Vs"
        Return "Reference stall speed / V_S" & CRLF & CRLF & "Definition: Reference 1-g calibrated airspeed at which the required lift coefficient equals CLmax for the selected aircraft mass and configuration. Nonnegative." & CRLF & CRLF & "Equation: V_{S,\mathrm{TAS}} = \sqrt{\frac{2 \, m \, g_0}{\rho \, S_{\mathrm{REF}} \, C_{L,\mathrm{MAX}}}}" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "Reynolds"
        Return "Reynolds number / Re" & CRLF & CRLF & "Definition: Ratio of inertial to viscous effects based on true airspeed and reference chord. Nonnegative." & CRLF & CRLF & "Equation: \mathrm{Re} = \frac{\rho \, \mathrm{TAS} \, c_{\mathrm{REF}}}{\mu}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Pressure Ratio δ"
        Return "Pressure ratio / δ" & CRLF & CRLF & "Definition: Ratio of local static pressure to standard sea-level pressure. Positive scalar." & CRLF & CRLF & "Equation: \delta = \frac{p}{p_0}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Density Ratio σ"
        Return "Density ratio / σ" & CRLF & CRLF & "Definition: Ratio of local air density to standard sea-level density. Positive scalar." & CRLF & CRLF & "Equation: \sigma = \frac{\rho}{\rho_0}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Temperature Ratio θ"
        Return "Temperature ratio / θ" & CRLF & CRLF & "Definition: Ratio of local absolute temperature to standard sea-level absolute temperature. Positive scalar." & CRLF & CRLF & "Equation: \theta = \frac{T}{T_0}" & CRLF & CRLF & "SI/reference unit: —"
    Case "Total Pressure"
        Return "Total pressure / p_T" & CRLF & CRLF & "Definition: Stagnation pressure of the air-relative flow under isentropic conditions." & CRLF & CRLF & "Equation: p_T = p + q_c" & CRLF & CRLF & "SI/reference unit: Pa"
    Case "DynPressure * S / g"
        Return "Dynamic pressure force equivalent / qS/g_0" & CRLF & CRLF & "Definition: Aerodynamic reference force qS expressed numerically in kilogram-force (kgf). Nonnegative." & CRLF & CRLF & "Equation: \frac{q \cdot S_{\mathrm{REF}}}{g_0}" & CRLF & CRLF & "SI/reference unit: kgf"
    Case "Lift Force"
        Return "Lift force / L" & CRLF & CRLF & "Definition: Aerodynamic lift force required by the selected load factor. Positive: lift toward the aircraft upper side." & CRLF & CRLF & "Equation: \frac{L}{g_0} = \frac{q \cdot S_{\mathrm{REF}} \cdot C_L}{g_0} = n \cdot m" & CRLF & CRLF & "SI/reference unit: kgf"
    Case "Weight/Delta W/δ"
        Return "Weight divided by pressure ratio / W/δ" & CRLF & CRLF & "Definition: Aircraft weight divided by atmospheric pressure ratio δ. Positive for positive aircraft weight." & CRLF & CRLF & "Equation: \frac{W}{\delta \cdot g_0} = \frac{m}{\delta}" & CRLF & CRLF & "SI/reference unit: kgf"
    Case "Load Factor Nz"
        Return "Normal load factor / N_Z" & CRLF & CRLF & "Definition: Ratio of aerodynamic lift to aircraft weight. Positive: lift toward the aircraft upper side." & CRLF & CRLF & "Equation: n = \frac{L}{W} = \frac{1}{\cos \varphi}" & CRLF & CRLF & "SI/reference unit: g"
    Case "Turn Radius"
        Return "Turn radius / r" & CRLF & CRLF & "Definition: Signed radius of a coordinated level turn relative to the air mass. Positive: right turn. Negative: left turn." & CRLF & CRLF & "Equation: r = \frac{\mathrm{TAS}^2}{g_0 \tan \varphi}" & CRLF & CRLF & "SI/reference unit: m"
    Case "Turn Rate"
        Return "Turn rate / ω" & CRLF & CRLF & "Definition: Rate of change of aircraft heading in a coordinated level turn. Positive: clockwise (right turn)." & CRLF & CRLF & "Equation: \omega = \frac{g_0 \tan \varphi}{\mathrm{TAS}}" & CRLF & CRLF & "SI/reference unit: rad/s"
    Case "AlongTrack Headwind"
        Return "Along-track headwind / HW_χ" & CRLF & CRLF & "Definition: Wind component along the aircraft ground track. Positive: wind from ahead. Negative: tailwind." & CRLF & CRLF & "Equation: \mathrm{HW}_\chi = V_W \cos(\psi_W - \chi)" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "AlongTrack Crosswind"
        Return "Along-track crosswind / CW_χ" & CRLF & CRLF & "Definition: Wind component perpendicular to the aircraft ground track. Positive: wind coming from the right. Negative: wind from the left." & CRLF & CRLF & "Equation: \mathrm{CW}_\chi = V_W \sin(\psi_W - \chi)" & CRLF & CRLF & "SI/reference unit: m/s"
    Case "mass.MTOW"
        Return "Maximum takeoff weight / m_{TO}" & CRLF & CRLF & "Definition: Maximum takeoff weight approved for the aircraft, expressed as mass in the selected units." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "mass.MLW"
        Return "Maximum landing weight / m_L" & CRLF & CRLF & "Definition: Maximum landing weight approved for the aircraft, expressed as mass in the selected units." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "mass.MZFW"
        Return "Maximum zero-fuel weight / m_{ZFW}" & CRLF & CRLF & "Definition: Maximum zero-fuel weight, excluding usable fuel, expressed as mass in the selected units." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "mass.BOW"
        Return "Basic operating weight / m_{BOW}" & CRLF & CRLF & "Definition: Basic Operating Weight as defined by the aircraft manufacturer." & CRLF & CRLF & "SI/reference unit: kg"
    Case "mass.Heavy"
        Return "Heavy reference weight / m_{HEAVY}" & CRLF & CRLF & "Definition: User-defined heavy reference weight, expressed as mass in the selected units." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "mass.Light"
        Return "Light reference weight / m_{LIGHT}" & CRLF & CRLF & "Definition: User-defined light reference weight, expressed as mass in the selected units." & CRLF & CRLF & "Equation: W = m \cdot g_0 \quad (\text{weight})" & CRLF & CRLF & "SI/reference unit: kg"
    Case "CLmaxFlap"
        Return "Maximum lift coefficient by flap setting / C_{L,MAX}" & CRLF & CRLF & "Definition: Maximum lift coefficient for the specified flap configuration. Positive coefficient." & CRLF & CRLF & "Equation: V_{S,\mathrm{TAS}} = \sqrt{\frac{2 \, m \, g_0}{\rho \, S_{\mathrm{REF}} \, C_{L,\mathrm{MAX}}}}" & CRLF & CRLF & "SI/reference unit: —"
    Case Else
        Return "No help text is available for this item."
    End Select
End Sub
