// Help catalog, maintained by hand. Keep in sync with AeroNames.bas and docs/quantity_catalog.json.
export interface CatalogItem {
  title: string;
  desc: string;
  eq: string;
  unit: string;
}

export const CATALOG: Record<string, CatalogItem> = {
  "Pressure Altitude": {
    title: "Pressure altitude \u2022 H<sub class='hp-sub'>P</sub>",
    desc: "ISA altitude corresponding to the local static pressure. Positive: pressure below ISA sea-level pressure.",
    eq: "pISA(Hp) = p",
    unit: "m",
  },
  "Geometric Altitude": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric height above mean sea level. Positive: above mean sea level.",
    eq: "h = r H / (r \u2212 H)",
    unit: "m",
  },
  "Pressure": {
    title: "Static pressure \u2022 P",
    desc: "Absolute static pressure of the surrounding air, related to density and absolute temperature by the ideal gas law.",
    eq: "p = \u03c1 R T",
    unit: "Pa",
  },
  "Temperature": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Static temperature of the surrounding air.",
    eq: "T = TISA(Hp) + \u0394T",
    unit: "K",
  },
  "Delta ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Difference between actual static air temperature and ISA temperature at the same pressure altitude. Positive: warmer than ISA.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    unit: "K",
  },

  "True Airspeed": {
    title: "True airspeed \u2022 TAS",
    desc: "Magnitude of aircraft velocity relative to the surrounding air. Nonnegative.",
    eq: "TAS = M a",
    unit: "m/s",
  },
  "Calibrated Airspeed": {
    title: "Calibrated airspeed \u2022 CAS",
    desc: "Airspeed at ISA sea-level conditions producing the same impact pressure as the actual flight condition, using the subsonic isentropic Pitot relation. Nonnegative.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    unit: "m/s",
  },
  "Equivalent Airspeed": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Airspeed at ISA sea-level conditions producing the same dynamic pressure as the actual flight condition. Nonnegative.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    unit: "m/s",
  },
  "Lift Coefficient CL": {
    title: "Lift coefficient \u2022 C<sub>L</sub>",
    desc: "Aerodynamic lift divided by the product of dynamic pressure and wing reference area. Positive: lift toward the aircraft upper side.",
    eq: "CL = n m g0 / (q S)",
    unit: "\u2014",
  },
  "Dynamic Pressure": {
    title: "Dynamic pressure \u2022 q",
    desc: "Kinetic energy per unit volume of the air-relative flow. Nonnegative.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    unit: "Pa",
  },
  "Impact Pressure": {
    title: "Impact pressure \u2022 q<sub>c</sub>",
    desc: "Difference between stagnation pressure and static pressure. Nonnegative in the adopted subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    unit: "Pa",
  },
  "Bank Angle \u03c6": {
    title: "Level turn bank angle \u2022 \u03c6",
    desc: "Aircraft bank angle in a coordinated level turn. Positive: right wing down.",
    eq: "n = 1 / cos \u03c6",
    unit: "rad",
  },
  "Track Angle": {
    title: "Ground track angle \u2022 χ",
    desc: "Direction of the aircraft horizontal ground-velocity vector, measured clockwise from true north. Positive: clockwise (ground-velocity vector to the right).",
    eq: "\\vec{V}_{\\mathrm{ground}} = \\vec{V}_{\\mathrm{air}} + \\vec{V}_{\\mathrm{wind}}",
    unit: "rad",
  },
  "Heading Angle \u03a8": {
    title: "Aircraft heading \u2022 ψ",
    desc: "Direction in which the aircraft nose points, measured clockwise from true north. Positive: clockwise (nose to the right).",
    eq: "\\psi = \\text{aircraft heading}",
    unit: "rad",
  },
  "Drift Angle": {
    title: "Drift angle \u2022 drift",
    desc: "Angular difference between heading and ground track (heading minus track). Positive: heading to the right of track.",
    eq: "\\mathrm{drift} = \\psi - \\chi",
    unit: "rad",
  },
  "Sideslip Angle \u03b2": {
    title: "Sideslip angle \u2022 β",
    desc: "Angle between the aircraft longitudinal axis and the incoming relative wind. Positive: relative wind coming from the right.",
    eq: "\\beta = \\text{sideslip angle}",
    unit: "rad",
  },
  "Ground Speed": {
    title: "Ground speed \u2022 GS",
    desc: "Magnitude of aircraft horizontal velocity relative to the ground. Nonnegative.",
    eq: "Vground = Vair + Vwind",
    unit: "m/s",
  },
  "Vs Factor": {
    title: "Stall speed factor \u2022 V<sub>S</sub> Factor",
    desc: "Input multiplier applied to reference 1-g stall speed in CAS, with an optional additive CAS increment specified in knots. Nonnegative multiplier.",
    eq: "CAS = factor \u00d7 V_S,CAS + \u0394CAS",
    unit: "\u2014",
  },
  "Mach": {
    title: "Mach number \u2022 Mach",
    desc: "Ratio of true airspeed to local speed of sound. Nonnegative.",
    eq: "M = TAS / a",
    unit: "\u2014",
  },
  "Wind Speed": {
    title: "Wind speed \u2022 V<sub>W</sub>",
    desc: "Magnitude of horizontal wind velocity. Nonnegative.",
    eq: "V_W = \\sqrt{\\mathrm{HW}^2 + \\mathrm{CW}^2}",
    unit: "m/s",
  },
  "Wind Direction": {
    title: "Wind direction from \u2022 wind from",
    desc: "Direction from which the wind blows, measured clockwise from true north. Positive: clockwise (wind-from direction to the right).",
    eq: "\\psi_W = \\text{meteorological wind direction}",
    unit: "rad",
  },
  "Geopotential Altitude": {
    title: "Geopotential altitude \u2022 H<sub>G</sub>",
    desc: "Altitude equivalent to gravitational potential energy per unit mass under constant standard gravity. Positive: above the reference datum.",
    eq: "H = r h / (r + h); for Hp/P input, H = Hp \u2212 29.271247 \u0394T ln(p/p0)",
    unit: "m",
  },
  "Density Altitude": {
    title: "Density altitude \u2022 H<sub>\u03c1</sub>",
    desc: "ISA altitude corresponding to the actual air density. Positive: above ISA sea level.",
    eq: "\u03c1ISA(H\u03c1) = \u03c1",
    unit: "m",
  },
  "Temperature Altitude": {
    title: "Temperature altitude \u2022 H<sub>T</sub>",
    desc: "Tropospheric ISA altitude corresponding to actual static temperature, limited to 11 km in this model. Positive: above ISA sea level.",
    eq: "TISA(HT) = T",
    unit: "m",
  },
  "Density": {
    title: "Air density \u2022 \u03c1",
    desc: "Mass of air per unit volume, calculated from static pressure and absolute temperature using the ideal gas law. Positive scalar.",
    eq: "\u03c1 = p / (R T)",
    unit: "kg/m\u00b3",
  },
  "Total Temperature": {
    title: "Total air temperature \u2022 TAT",
    desc: "Ideal stagnation temperature obtained by adiabatically bringing the air-relative flow to rest, without probe recovery corrections.",
    eq: "Tt = T (1 + (\u03b3\u22121) M\u00b2/2)",
    unit: "K",
  },
  "Viscosity": {
    title: "Dynamic viscosity \u2022 \u03bc",
    desc: "Dynamic viscosity of air relates shear stress to velocity gradient; its temperature dependence is modeled by Sutherland's law. Positive scalar.",
    eq: "\u03bc = \u03bc0 (T0 + C)/(T + C) (T/T0)^(3/2)",
    unit: "Pa\u00b7s",
  },
  "Sound Speed": {
    title: "Speed of sound \u2022 a",
    desc: "Speed of propagation of small pressure disturbances in the surrounding air. Positive scalar.",
    eq: "a = \u221a(\u03b3 R T)",
    unit: "m/s",
  },
  "Stall Speed Vs": {
    title: "Reference stall speed \u2022 V<sub>S</sub>",
    desc: "Reference 1-g calibrated airspeed at which the required lift coefficient equals CLmax for the selected aircraft mass and configuration. Nonnegative.",
    eq: "V_S,TAS = \u221a(2 m g0 / (\u03c1 S_REF C_L,MAX)); displayed V_S,CAS = CAS(V_S,TAS)",
    unit: "m/s",
  },
  "Reynolds": {
    title: "Reynolds number \u2022 Re",
    desc: "Ratio of inertial to viscous effects based on true airspeed and reference chord. Nonnegative.",
    eq: "Re = \u03c1 TAS c_REF / \u03bc",
    unit: "\u2014",
  },
  "Pressure Ratio \u03b4": {
    title: "Pressure ratio \u2022 \u03b4",
    desc: "Ratio of local static pressure to standard sea-level pressure. Positive scalar.",
    eq: "\u03b4 = p / p0",
    unit: "\u2014",
  },
  "Density Ratio \u03c3": {
    title: "Density ratio \u2022 \u03c3",
    desc: "Ratio of local air density to standard sea-level density. Positive scalar.",
    eq: "\u03c3 = \u03c1 / \u03c10",
    unit: "\u2014",
  },
  "Temperature Ratio \u03b8": {
    title: "Temperature ratio \u2022 \u03b8",
    desc: "Ratio of local absolute temperature to standard sea-level absolute temperature. Positive scalar.",
    eq: "\u03b8 = T / T0",
    unit: "\u2014",
  },
  "Total Pressure": {
    title: "Total pressure \u2022 pt",
    desc: "Stagnation pressure of the air-relative flow under isentropic conditions.",
    eq: "pt = p + qc",
    unit: "Pa",
  },
  "DynPressure * S / g": {
    title: "Dynamic pressure force equivalent \u2022 qS/g0",
    desc: "Aerodynamic reference force qS for a unit lift coefficient (CL = 1), expressed in kilogram-force (kgf). Nonnegative.",
    eq: "q S / g0 (displayed as kgf)",
    unit: "kgf",
  },
  "Lift Force": {
    title: "Lift force \u2022 L",
    desc: "Aerodynamic lift force required by the selected load factor. Positive: lift toward the aircraft upper side.",
    eq: "L / g0 = q S_REF C_L / g0 = n m (displayed as kgf)",
    unit: "kgf",
  },
  "Weight/Delta W/\u03b4": {
    title: "Weight divided by pressure ratio \u2022 W/\u03b4",
    desc: "Aircraft weight divided by atmospheric pressure ratio δ, expressed in kilogram-force (kgf). Positive for positive aircraft weight.",
    eq: "W / (\u03b4 g0) (displayed as kgf)",
    unit: "kgf",
  },
  "Load Factor Nz": {
    title: "Normal load factor \u2022 N<sub>Z</sub>",
    desc: "Ratio of aerodynamic lift to aircraft weight. Positive: lift toward the aircraft upper side.",
    eq: "n = 1 / cos \u03c6 (coordinated level turn)",
    unit: "g",
  },
  "Turn Radius": {
    title: "Turn radius \u2022 r",
    desc: "Signed radius of a coordinated level turn relative to the air mass. Positive: right turn. Negative: left turn.",
    eq: "r = TAS\u00b2 / (g0 tan \u03c6)",
    unit: "m",
  },
  "Turn Rate": {
    title: "Turn rate \u2022 \u03c9",
    desc: "Rate of change of aircraft heading in a coordinated level turn. Positive: clockwise (right turn).",
    eq: "\u03c9 = g0 tan \u03c6 / TAS",
    unit: "rad/s",
  },
  "AlongTrack Headwind": {
    title: "Along-track headwind \u2022 HW\u03c7",
    desc: "Wind component along the aircraft ground track. Positive: wind from ahead. Negative: tailwind.",
    eq: "Projection against ground track",
    unit: "m/s",
  },
  "AlongTrack Crosswind": {
    title: "Along-track crosswind \u2022 CW\u03c7",
    desc: "Wind component perpendicular to the aircraft ground track. Positive: wind coming from the right. Negative: wind from the left.",
    eq: "Projection across ground track",
    unit: "m/s",
  },
  "Hp": {
    title: "Pressure altitude \u2022 H<sub class='hp-sub'>P</sub>",
    desc: "ISA altitude corresponding to the local static pressure. Positive: pressure below ISA sea-level pressure.",
    eq: "pISA(Hp) = p",
    unit: "m",
  },
  "Hg": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric height above mean sea level. Positive: above mean sea level.",
    eq: "h = r0 H / (r0 \u2212 H)",
    unit: "m",
  },
  "Hgeom": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "h = r0 H / (r0 \u2212 H)",
    unit: "m",
  },
  "Hgeop": {
    title: "Geopotential altitude \u2022 H<sub>G</sub>",
    desc: "Effective gravitational altitude used by the standard atmosphere.",
    eq: "H = r h / (r + h); for Hp/P input, H = Hp \u2212 29.271247 \u0394T ln(p/p0)",
    unit: "m",
  },
  "P": {
    title: "Static pressure \u2022 P",
    desc: "Absolute static pressure of the surrounding air, related to density and absolute temperature by the ideal gas law.",
    eq: "p = \u03c1 R T",
    unit: "Pa",
  },
  "\u0394 ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Difference between actual static air temperature and ISA temperature at the same pressure altitude. Positive: warmer than ISA.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    unit: "K",
  },
  "OAT": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Static temperature of the surrounding air.",
    eq: "T = TISA(Hp) + \u0394T",
    unit: "K",
  },
  "TAS": {
    title: "True airspeed \u2022 TAS",
    desc: "Magnitude of aircraft velocity relative to the surrounding air. Nonnegative.",
    eq: "TAS = M a",
    unit: "m/s",
  },
  "CAS": {
    title: "Calibrated airspeed \u2022 CAS",
    desc: "Airspeed at ISA sea-level conditions producing the same impact pressure as the actual flight condition, using the subsonic isentropic Pitot relation. Nonnegative.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    unit: "m/s",
  },
  "EAS": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Airspeed at ISA sea-level conditions producing the same dynamic pressure as the actual flight condition. Nonnegative.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    unit: "m/s",
  },
  "CL": {
    title: "Lift coefficient \u2022 C<sub>L</sub>",
    desc: "Aerodynamic lift divided by the product of dynamic pressure and wing reference area. Positive: lift toward the aircraft upper side.",
    eq: "CL = n m g0 / (q S)",
    unit: "\u2014",
  },
  "Qdyn": {
    title: "Dynamic pressure \u2022 q",
    desc: "Kinetic energy per unit volume of the air-relative flow. Nonnegative.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    unit: "Pa",
  },
  "Qc": {
    title: "Impact pressure \u2022 q<sub>c</sub>",
    desc: "Difference between stagnation pressure and static pressure. Nonnegative in the adopted subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    unit: "Pa",
  },
  "Weight": {
    title: "Aircraft mass \u2022 m",
    desc: "Aircraft weight, expressed as mass in the selected units for aerodynamic calculations. Nonnegative.",
    eq: "W = m g0",
    unit: "kg",
  },
  "Sref": {
    title: "Wing reference area \u2022 S<sub>REF</sub>",
    desc: "Wing reference area used to define aerodynamic coefficients. Positive area.",
    eq: "L = q S_REF C_L",
    unit: "m\u00b2",
  },
  "cref": {
    title: "Reference chord \u2022 c<sub>REF</sub>",
    desc: "Wing reference chord used to calculate Reynolds number. Positive length.",
    eq: "Re = \u03c1 TAS c_REF / \u03bc",
    unit: "m",
  },
  "CLmax": {
    title: "Maximum lift coefficient \u2022 C<sub>L,MAX</sub>",
    desc: "Maximum lift coefficient attainable at the onset of stall for the selected aircraft configuration. Positive coefficient.",
    eq: "V_S,TAS = \u221a(2 m g0 / (\u03c1 S_REF C_L,MAX))",
    unit: "\u2014",
  },
  "NzPullup": {
    title: "Pull-up load factor \u2022 N<sub>Z</sub> (Pull-up)",
    desc: "Ratio of aerodynamic lift to aircraft weight in an unbanked maneuver. Positive: lift toward the aircraft upper side.",
    eq: "L = n m g0",
    unit: "g",
  },
  "NzTurn": {
    title: "Level turn load factor \u2022 N<sub>Z</sub> (Turn)",
    desc: "Load factor in a coordinated level turn. Positive and not less than 1 in the adopted model.",
    eq: "n = 1 / cos \u03c6",
    unit: "g",
  },
  "BankTurn": {
    title: "Level turn bank angle \u2022 \u03c6",
    desc: "Aircraft bank angle in a coordinated level turn. Positive: right wing down.",
    eq: "n = 1 / cos \u03c6",
    unit: "rad",
  },
  "Track": {
    title: "Ground track angle \u2022 χ",
    desc: "Direction of the aircraft horizontal ground-velocity vector, measured clockwise from true north. Positive: clockwise (ground-velocity vector to the right).",
    eq: "\\vec{V}_{\\mathrm{ground}} = \\vec{V}_{\\mathrm{air}} + \\vec{V}_{\\mathrm{wind}}",
    unit: "rad",
  },
  "Heading": {
    title: "Aircraft heading \u2022 ψ",
    desc: "Direction in which the aircraft nose points, measured clockwise from true north. Positive: clockwise (nose to the right).",
    eq: "\\psi = \\text{aircraft heading}",
    unit: "rad",
  },
  "Sideslip": {
    title: "Sideslip angle \u2022 β",
    desc: "Angle between the aircraft longitudinal axis and the incoming relative wind. Positive: relative wind coming from the right.",
    eq: "\\beta = \\text{sideslip angle}",
    unit: "rad",
  },
  "Drift": {
    title: "Drift angle \u2022 drift",
    desc: "Angular difference between heading and ground track (heading minus track). Positive: heading to the right of track.",
    eq: "\\mathrm{drift} = \\psi - \\chi",
    unit: "rad",
  },
  "HeadWind": {
    title: "Reference headwind \u2022 HW",
    desc: "Wind component along the selected runway/reference direction. Positive: wind from ahead. Negative: tailwind.",
    eq: "\\mathrm{HW} = V_W \\cos(\\psi_W - \\psi_{\\mathrm{RWY}})",
    unit: "m/s",
  },
  "CrossWind": {
    title: "Reference crosswind \u2022 CW",
    desc: "Wind component perpendicular to the selected runway/reference direction. Positive: wind coming from the right. Negative: wind from the left.",
    eq: "\\mathrm{CW} = V_W \\sin(\\psi_W - \\psi_{\\mathrm{RWY}})",
    unit: "m/s",
  },
  "Runway Angle": {
    title: "Runway reference angle \u2022 RWY",
    desc: "Direction of the selected runway/reference axis, measured clockwise from true north. Positive: clockwise (reference direction to the right).",
    eq: "\\psi_{\\mathrm{RWY}} = \\text{runway heading}",
    unit: "rad",
  },
  "Aircraft Profile": {
    title: "Aircraft Profile • Geometry & Weights",
    desc: "Saved aircraft aerodynamic and mass configuration. Supplies the wing reference area, reference chord (MAC), operating masses, and flap C_L,MAX values.",
    eq: "L = q \\cdot S_{\\mathrm{REF}} \\cdot C_L",
    unit: "m², m, kg",
  },
  "mass.MTOW": {
    title: "Maximum takeoff weight • MTOW",
    desc: "Maximum takeoff weight approved for the aircraft, expressed as mass in the selected units.",
    eq: "",
    unit: "kg",
  },
  "mass.MLW": {
    title: "Maximum landing weight • MLW",
    desc: "Maximum landing weight approved for the aircraft, expressed as mass in the selected units.",
    eq: "",
    unit: "kg",
  },
  "mass.MZFW": {
    title: "Maximum zero-fuel weight • MZFW",
    desc: "Maximum zero-fuel weight, excluding usable fuel, expressed as mass in the selected units.",
    eq: "",
    unit: "kg",
  },
  "mass.BOW": {
    title: "Basic operating weight • BOW",
    desc: "Basic Operating Weight as defined by the aircraft manufacturer, expressed as mass in the selected units.",
    eq: "",
    unit: "kg",
  },
  "mass.Heavy": {
    title: "Heavy reference weight • Heavy",
    desc: "User-defined heavy reference weight, expressed as mass in the selected units. Not a certified weight limit.",
    eq: "",
    unit: "kg",
  },
  "mass.Light": {
    title: "Light reference weight • Light",
    desc: "User-defined light reference weight, expressed as mass in the selected units. Not a certified weight limit.",
    eq: "",
    unit: "kg",
  },
  "CLmaxFlap": {
    title: "Maximum lift coefficient • C<sub>L,MAX</sub>",
    desc: "Maximum lift coefficient for the specified flap configuration, supplied from aircraft aerodynamic data. Positive coefficient.",
    eq: "Vs = √(2 m g₀ / (ρ S C_{L,MAX}))",
    unit: "—",
  },
  "Vs Factor Output": {
    title: "Stall speed factor • V<sub>S</sub> Factor",
    desc: "Ratio of current calibrated airspeed to reference 1-g stall speed in CAS. Nonnegative.",
    eq: "",
    unit: "—",
  },
};
