// Auto-generated catalog from docs/quantity_catalog.json
export interface CatalogItem {
  title: string;
  desc: string;
  eq: string;
  model: string;
  unit: string;
}

export const CATALOG: Record<string, CatalogItem> = {
  "Pressure Altitude": {
    title: "Pressure altitude \u2022 H<sub class='hp-sub'>P</sub>",
    desc: "Pressure altitude: altitude in the ISA atmosphere corresponding to the entered static pressure.",
    eq: "pISA(Hp) = p",
    model: "Hydrostatic balance relates pressure to altitude in the layered ISA atmosphere. Inverting that pressure profile gives an equivalent pressure altitude, not a measurement of height above the ground.",
    unit: "m",
  },
  "Geometric Altitude": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "h = r H / (r \u2212 H)",
    model: "Geometric height measures distance above sea level. The spherical-Earth conversion accounts for weakening gravity when converting between geometric and geopotential altitude.",
    unit: "m",
  },
  "Pressure": {
    title: "Static pressure \u2022 P",
    desc: "Static atmospheric pressure. AeroCalculator converts it to pressure altitude.",
    eq: "p = \u03c1 R T",
    model: "The ISA hydrostatic pressure profile represents the weight of the air column above the selected level. Local density then follows the ideal-gas relation using the entered temperature.",
    unit: "Pa",
  },
  "Temperature": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Outside air temperature at the aircraft condition.",
    eq: "T = TISA(Hp) + \u0394T",
    model: "Static air temperature sets density and sound speed. Adding the ISA temperature offset gives the local temperature without changing the selected pressure level.",
    unit: "K",
  },
  "Delta ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Temperature deviation from the ISA temperature at the current pressure altitude.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    model: "The temperature offset changes the local thermal state at the same pressure altitude. Warmer air at fixed pressure has lower density; colder air has higher density.",
    unit: "K",
  },

  "True Airspeed": {
    title: "True airspeed \u2022 TAS",
    desc: "True Airspeed: aircraft speed relative to the surrounding air mass.",
    eq: "TAS = M a",
    model: "True airspeed measures motion through the air mass. Combining it with local density sets dynamic pressure; combining it with local sound speed gives Mach number.",
    unit: "m/s",
  },
  "Calibrated Airspeed": {
    title: "Calibrated airspeed \u2022 CAS",
    desc: "Indicated airspeed corrected for instrument and position errors. CAS is related to impact pressure using standard sea-level references.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    model: "CAS is the speed in standard sea-level air that produces the same pitot impact pressure. The subsonic isentropic conversion accounts for compression as the flow is brought to rest.",
    unit: "m/s",
  },
  "Equivalent Airspeed": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Equivalent Airspeed: speed at standard sea-level density with the same dynamic pressure as the current flight condition.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    model: "EAS preserves dynamic pressure when replacing the actual density with standard sea-level density. Equal EAS gives equal aerodynamic force for the same area and lift coefficient.",
    unit: "m/s",
  },
  "Lift Coefficient CL": {
    title: "Lift coefficient \u2022 C<sub>L</sub>",
    desc: "Lift coefficient. With mass, load factor and reference area, it defines the required dynamic pressure.",
    eq: "CL = n m g0 / (q S)",
    model: "The lift equation balances aerodynamic lift against the selected normal load, n times weight. Increasing mass or load factor requires more dynamic pressure or a larger lift coefficient.",
    unit: "\u2014",
  },
  "Dynamic Pressure": {
    title: "Dynamic pressure \u2022 q",
    desc: "Dynamic pressure q = \u00bd\u03c1\u00b7TAS\u00b2.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    model: "Dynamic pressure is kinetic energy per unit volume of moving air. It scales aerodynamic forces and rises with density and the square of true airspeed.",
    unit: "Pa",
  },
  "Impact Pressure": {
    title: "Impact pressure \u2022 q<sub>c</sub>",
    desc: "Impact pressure qc = total pressure minus static pressure for the documented subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    model: "A pitot opening brings the flow to rest and converts kinetic energy into compression. Impact pressure is stagnation minus static pressure; it approaches dynamic pressure at low Mach number.",
    unit: "Pa",
  },
  "Bank Angle \u03c6": {
    title: "Level turn bank angle \u2022 \u03c6",
    desc: "Bank angle for a coordinated level turn. Load factor is derived from n = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "In a coordinated level turn, the vertical component of lift balances weight and the horizontal component provides centripetal acceleration. This gives n = 1/cos(bank), with bank magnitude below 90 degrees.",
    unit: "rad",
  },
  "Track Angle": {
    title: "Ground track angle \u2022 χ",
    desc: "Track angle: direction of the ground-velocity vector.",
    eq: "\\vec{V}_{\\mathrm{ground}} = \\vec{V}_{\\mathrm{air}} + \\vec{V}_{\\mathrm{wind}}",
    model: "Track is the direction of the ground-velocity vector. Wind shifts it away from the air-relative direction through the horizontal wind triangle.",
    unit: "rad",
  },
  "Heading Angle \u03a8": {
    title: "Aircraft heading \u2022 ψ",
    desc: "Heading angle: direction the aircraft longitudinal axis points.",
    eq: "\\psi = \\text{aircraft heading}",
    model: "Heading describes the aircraft longitudinal axis. Sideslip relates that axis to the air-relative velocity, and wind then determines the ground track.",
    unit: "rad",
  },
  "Drift Angle": {
    title: "Drift angle \u2022 drift",
    desc: "Drift angle: heading minus track.",
    eq: "\\mathrm{drift} = \\psi - \\chi",
    model: "Drift is heading minus ground track. It combines the effects of wind and the selected sideslip rather than describing a force or an aerodynamic coefficient.",
    unit: "rad",
  },
  "Sideslip Angle \u03b2": {
    title: "Sideslip angle \u2022 β",
    desc: "Sideslip angle β: angle between the aircraft heading and the air-relative velocity direction.",
    eq: "\\beta = \\text{sideslip angle}",
    model: "Sideslip is the angular difference between the aircraft axis and its air-relative motion. The wind triangle uses it to orient the airspeed vector; it does not calculate side force or yaw dynamics.",
    unit: "rad",
  },
  "Ground Speed": {
    title: "Ground speed \u2022 GS",
    desc: "Aircraft speed relative to the ground: the air-relative velocity plus the wind.",
    eq: "Vground = Vair + Vwind",
    model: "The ground-velocity vector is the sum of air-relative velocity and wind velocity. Directions and sideslip determine the vector components; scalar speeds cannot simply be added for arbitrary wind angles.",
    unit: "m/s",
  },
  "Vs Factor": {
    title: "Stall speed factor \u2022 V<sub>S</sub> Factor",
    desc: "Multiplier applied to the 1-g calibrated stall speed. The optional +\u0394 term is added in knots.",
    eq: "CAS = factor \u00d7 V_S,CAS + \u0394CAS",
    model: "The multiplier scales the 1-g stall reference expressed as CAS; the optional delta adds a fixed speed in knots. It specifies a speed margin and does not by itself prescribe a maneuver load factor.",
    unit: "\u2014",
  },
  "Mach": {
    title: "Mach number \u2022 Mach",
    desc: "Mach number: True Airspeed divided by the local speed of sound.",
    eq: "M = TAS / a",
    model: "Mach compares airspeed with the speed of pressure disturbances in the local air. The pitot conversion used here describes subsonic, isentropic deceleration with gamma = 1.4.",
    unit: "\u2014",
  },
  "Wind Speed": {
    title: "Wind speed \u2022 V<sub>W</sub>",
    desc: "Wind-vector magnitude. Use Wind Direction for its direction.",
    eq: "V_W = \\sqrt{\\mathrm{HW}^2 + \\mathrm{CW}^2}",
    model: "Wind speed is the magnitude of the horizontal wind vector. Resolving or combining its perpendicular components preserves that vector magnitude.",
    unit: "m/s",
  },
  "Wind Direction": {
    title: "Wind direction from \u2022 wind from",
    desc: "Direction from which the wind is referenced in the wind-vector input mode.",
    eq: "\\psi_W = \\text{meteorological wind direction}",
    model: "Wind direction follows the meteorological convention: the direction the wind comes from. The velocity vector points the opposite way; zero wind has no physical direction.",
    unit: "rad",
  },
  "Geopotential Altitude": {
    title: "Geopotential altitude \u2022 H<sub>G</sub>",
    desc: "Effective gravitational altitude used by the standard atmosphere.",
    eq: "H = r h / (r + h); for Hp/P input, H = Hp \u2212 29.271247 \u0394T ln(p/p0)",
    model: "Geopotential height expresses gravitational potential as an equivalent height at standard gravity. For pressure-altitude input, the temperature correction represents the changed thickness of a warmer or colder air column.",
    unit: "m",
  },
  "Density Altitude": {
    title: "Density altitude \u2022 H<sub>\u03c1</sub>",
    desc: "ISA altitude with the same density as the current condition.",
    eq: "\u03c1ISA(H\u03c1) = \u03c1",
    model: "Density altitude is the ISA level with the same air density as the current condition. It summarizes density effects on aerodynamic forces without claiming that the aircraft is physically at that height.",
    unit: "m",
  },
  "Temperature Altitude": {
    title: "Temperature altitude \u2022 H<sub>T</sub>",
    desc: "Altitude returned by the documented temperature-altitude convention. Temperature alone is not a unique altitude across all layers.",
    eq: "TISA(HT) = T",
    model: "This is a tropospheric temperature-equivalent height, using the ISA lapse rate. Temperatures at or below 216.65 K return 11 km in this convention; temperature alone cannot identify a unique altitude across all ISA layers.",
    unit: "m",
  },
  "Density": {
    title: "Air density \u2022 \u03c1",
    desc: "Mass of air per unit volume.",
    eq: "\u03c1 = p / (R T)",
    model: "The ideal-gas equation links density to static pressure and absolute temperature for dry air. At the same pressure, heating expands the air and reduces its mass per unit volume.",
    unit: "kg/m\u00b3",
  },
  "Total Temperature": {
    title: "Total air temperature \u2022 TAT",
    desc: "Isentropic stagnation temperature for a calorically perfect gas.",
    eq: "Tt = T (1 + (\u03b3\u22121) M\u00b2/2)",
    model: "Adiabatic deceleration converts kinetic energy into internal energy, raising temperature as the air is brought to rest. The ideal stagnation relation uses a constant specific-heat ratio of 1.4, without a probe recovery correction.",
    unit: "K",
  },
  "Viscosity": {
    title: "Dynamic viscosity \u2022 \u03bc",
    desc: "Dynamic viscosity from the documented temperature correlation.",
    eq: "\u03bc = \u03bc0 (T0 + C)/(T + C) (T/T0)^(3/2)",
    model: "Sutherland correlation represents the temperature dependence of molecular momentum transport in air. Dynamic viscosity increases with temperature and supplies the viscous scale in Reynolds number.",
    unit: "Pa\u00b7s",
  },
  "Sound Speed": {
    title: "Speed of sound \u2022 a",
    desc: "Local speed of sound in the ideal-gas model.",
    eq: "a = \u221a(\u03b3 R T)",
    model: "Small pressure disturbances propagate through ideal air at a speed set by absolute temperature and the specific-heat ratio. Warmer air has a higher sound speed.",
    unit: "m/s",
  },
  "Stall Speed Vs": {
    title: "Reference stall speed \u2022 V<sub>S</sub>",
    desc: "1-g reference stall speed displayed as CAS, independent of maneuver load factor.",
    eq: "V_S,TAS = \u221a(2 m g0 / (\u03c1 S_REF C_L,MAX)); displayed V_S,CAS = CAS(V_S,TAS)",
    model: "At the 1-g stall reference, maximum lift just balances weight. The result is converted from TAS to CAS; maneuver load factor does not alter this reference value.",
    unit: "m/s",
  },
  "Reynolds": {
    title: "Reynolds number \u2022 Re",
    desc: "Ratio of inertial and viscous effects based on reference chord.",
    eq: "Re = \u03c1 TAS c_REF / \u03bc",
    model: "Reynolds number compares inertial and viscous effects over the reference chord. Increasing speed, density, or chord increases this ratio; increasing viscosity reduces it.",
    unit: "\u2014",
  },
  "Pressure Ratio \u03b4": {
    title: "Pressure ratio \u2022 \u03b4",
    desc: "Pressure divided by standard sea-level pressure.",
    eq: "\u03b4 = p / p0",
    model: "Dividing static pressure by standard sea-level pressure gives a dimensionless atmospheric pressure scale. It is used to normalize weight and compare conditions across pressure levels.",
    unit: "\u2014",
  },
  "Density Ratio \u03c3": {
    title: "Density ratio \u2022 \u03c3",
    desc: "Density divided by standard sea-level density.",
    eq: "\u03c3 = \u03c1 / \u03c10",
    model: "The density ratio compares local air density with standard sea-level density. Its square root relates true and equivalent airspeed at equal dynamic pressure.",
    unit: "\u2014",
  },
  "Temperature Ratio \u03b8": {
    title: "Temperature ratio \u2022 \u03b8",
    desc: "Absolute temperature divided by standard sea-level temperature.",
    eq: "\u03b8 = T / T0",
    model: "The temperature ratio compares absolute local temperature with the standard sea-level temperature. Absolute temperature is required because molecular thermal energy sets sound speed and the ideal-gas density relation.",
    unit: "\u2014",
  },
  "Total Pressure": {
    title: "Total pressure \u2022 pt",
    desc: "Stagnation pressure from the subsonic isentropic relation.",
    eq: "pt = p + qc",
    model: "Stagnation pressure is the pressure after ideal subsonic, isentropic deceleration to rest. Adding pitot impact pressure to static pressure gives this total pressure; shocks and flow losses are not modeled.",
    unit: "Pa",
  },
  "DynPressure * S / g": {
    title: "Dynamic pressure force equivalent \u2022 qS/g0",
    desc: "Dynamic pressure times reference area, expressed as force in kgf.",
    eq: "q S / g0 (displayed as kgf)",
    model: "Dynamic pressure times reference area gives an aerodynamic force scale before multiplying by a force coefficient. Dividing by standard gravity expresses that force in kgf; it is not aircraft mass.",
    unit: "kgf",
  },
  "Lift Force": {
    title: "Lift force \u2022 L",
    desc: "Lift required by the selected mass and maneuver, displayed in kgf.",
    eq: "L / g0 = q S_REF C_L / g0 = n m (displayed as kgf)",
    model: "Lift is dynamic pressure times reference area and lift coefficient, and equals the selected normal load times weight. The displayed kgf value converts that force using standard gravity.",
    unit: "kgf",
  },
  "Weight/Delta W/\u03b4": {
    title: "Weight divided by pressure ratio \u2022 W/\u03b4",
    desc: "Weight normalized by pressure ratio, displayed in kgf.",
    eq: "W / (\u03b4 g0) (displayed as kgf)",
    model: "Dividing weight by pressure ratio normalizes the aircraft load to standard sea-level pressure. The kgf display is a force normalization, not a change in the actual aircraft mass.",
    unit: "kgf",
  },
  "Load Factor Nz": {
    title: "Normal load factor \u2022 N<sub>Z</sub>",
    desc: "Selected normal load factor. In a coordinated level turn, the load factor follows the selected bank angle or determines the bank angle.",
    eq: "n = 1 / cos \u03c6 (coordinated level turn)",
    model: "Normal load factor measures lift relative to weight. In the level-turn mode it follows the vertical lift balance; in pull-up mode it is supplied directly.",
    unit: "g",
  },
  "Turn Radius": {
    title: "Turn radius \u2022 r",
    desc: "Signed level-turn radius, unavailable at zero bank.",
    eq: "r = TAS\u00b2 / (g0 tan \u03c6)",
    model: "The horizontal component of lift supplies centripetal acceleration in a coordinated level turn. More bank tightens the turn at a fixed TAS; zero bank gives no finite turn radius.",
    unit: "m",
  },
  "Turn Rate": {
    title: "Turn rate \u2022 \u03c9",
    desc: "Signed angular turn rate under the level-turn assumption.",
    eq: "\u03c9 = g0 tan \u03c6 / TAS",
    model: "Turn rate is the angular response to the centripetal acceleration supplied by banked lift. At a fixed bank, increasing TAS reduces the rate; the sign follows the selected turn direction.",
    unit: "rad/s",
  },
  "AlongTrack Headwind": {
    title: "Along-track headwind \u2022 HW\u03c7",
    desc: "Positive headwind opposes travel along the calculated track.",
    eq: "Projection against ground track",
    model: "Projecting wind against the calculated ground track gives the along-track headwind. Positive headwind reduces the ground-speed component relative to motion through the air.",
    unit: "m/s",
  },
  "AlongTrack Crosswind": {
    title: "Along-track crosswind \u2022 CW\u03c7",
    desc: "Signed crosswind component in the documented convention.",
    eq: "Projection across ground track",
    model: "Projecting wind perpendicular to the calculated ground track gives its signed lateral component. This is a change of reference axes, not an additional wind velocity.",
    unit: "m/s",
  },
  "Hp": {
    title: "Pressure altitude \u2022 H<sub class='hp-sub'>P</sub>",
    desc: "Pressure altitude: altitude in the ISA atmosphere corresponding to the entered static pressure.",
    eq: "pISA(Hp) = p",
    model: "Hydrostatic balance relates pressure to altitude in the layered ISA atmosphere. Inverting that pressure profile gives an equivalent pressure altitude, not a measurement of height above the ground.",
    unit: "m",
  },
  "Hg": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "h = r0 H / (r0 \u2212 H)",
    model: "Geometric height measures distance above sea level. The spherical-Earth conversion accounts for weakening gravity when converting between geometric and geopotential altitude.",
    unit: "m",
  },
  "Hgeom": {
    title: "Geometric altitude \u2022 H<sub>GEOM</sub>",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "h = r0 H / (r0 \u2212 H)",
    model: "Geometric height measures distance above sea level. The spherical-Earth conversion accounts for weakening gravity when converting between geometric and geopotential altitude.",
    unit: "m",
  },
  "Hgeop": {
    title: "Geopotential altitude \u2022 H<sub>G</sub>",
    desc: "Effective gravitational altitude used by the standard atmosphere.",
    eq: "H = r h / (r + h); for Hp/P input, H = Hp \u2212 29.271247 \u0394T ln(p/p0)",
    model: "Geopotential height expresses gravitational potential as an equivalent height at standard gravity. For pressure-altitude input, the temperature correction represents the changed thickness of a warmer or colder air column.",
    unit: "m",
  },
  "P": {
    title: "Static pressure \u2022 P",
    desc: "Static atmospheric pressure. AeroCalculator converts it to pressure altitude.",
    eq: "p = \u03c1 R T",
    model: "The ISA hydrostatic pressure profile represents the weight of the air column above the selected level. Local density then follows the ideal-gas relation using the entered temperature.",
    unit: "Pa",
  },
  "\u0394 ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Temperature deviation from the ISA temperature at the current pressure altitude.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    model: "The temperature offset changes the local thermal state at the same pressure altitude. Warmer air at fixed pressure has lower density; colder air has higher density.",
    unit: "K",
  },
  "OAT": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Outside air temperature at the aircraft condition.",
    eq: "T = TISA(Hp) + \u0394T",
    model: "Static air temperature sets density and sound speed. Adding the ISA temperature offset gives the local temperature without changing the selected pressure level.",
    unit: "K",
  },
  "TAS": {
    title: "True airspeed \u2022 TAS",
    desc: "True Airspeed: aircraft speed relative to the surrounding air mass.",
    eq: "TAS = M a",
    model: "True airspeed measures motion through the air mass. Combining it with local density sets dynamic pressure; combining it with local sound speed gives Mach number.",
    unit: "m/s",
  },
  "CAS": {
    title: "Calibrated airspeed \u2022 CAS",
    desc: "Indicated airspeed corrected for instrument and position errors. CAS is related to impact pressure using standard sea-level references.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    model: "CAS is the speed in standard sea-level air that produces the same pitot impact pressure. The subsonic isentropic conversion accounts for compression as the flow is brought to rest.",
    unit: "m/s",
  },
  "EAS": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Equivalent Airspeed: speed at standard sea-level density with the same dynamic pressure as the current flight condition.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    model: "EAS preserves dynamic pressure when replacing the actual density with standard sea-level density. Equal EAS gives equal aerodynamic force for the same area and lift coefficient.",
    unit: "m/s",
  },
  "CL": {
    title: "Lift coefficient \u2022 C<sub>L</sub>",
    desc: "Lift coefficient. With mass, load factor and reference area, it defines the required dynamic pressure.",
    eq: "CL = n m g0 / (q S)",
    model: "The lift equation balances aerodynamic lift against the selected normal load, n times weight. Increasing mass or load factor requires more dynamic pressure or a larger lift coefficient.",
    unit: "\u2014",
  },
  "Qdyn": {
    title: "Dynamic pressure \u2022 q",
    desc: "Dynamic pressure q = \u00bd\u03c1\u00b7TAS\u00b2.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    model: "Dynamic pressure is kinetic energy per unit volume of moving air. It scales aerodynamic forces and rises with density and the square of true airspeed.",
    unit: "Pa",
  },
  "Qc": {
    title: "Impact pressure \u2022 q<sub>c</sub>",
    desc: "Impact pressure qc = total pressure minus static pressure for the documented subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    model: "A pitot opening brings the flow to rest and converts kinetic energy into compression. Impact pressure is stagnation minus static pressure; it approaches dynamic pressure at low Mach number.",
    unit: "Pa",
  },
  "Weight": {
    title: "Aircraft mass \u2022 m",
    desc: "Aircraft mass used for lift, stall-speed and maneuver calculations.",
    eq: "W = m g0",
    model: "The entered quantity is mass; multiplying by standard gravity gives weight. The selected normal load factor then sets the lift required by the maneuver.",
    unit: "kg",
  },
  "Sref": {
    title: "Wing reference area \u2022 S<sub>REF</sub>",
    desc: "Wing reference area used in aerodynamic force and coefficient calculations.",
    eq: "L = q S_REF C_L",
    model: "Reference area is the chosen normalization area in the lift equation. A larger area produces more lift at the same dynamic pressure and lift coefficient; it does not determine wing shape.",
    unit: "m\u00b2",
  },
  "cref": {
    title: "Reference chord \u2022 c<sub>REF</sub>",
    desc: "Wing reference chord used to calculate Reynolds number.",
    eq: "Re = \u03c1 TAS c_REF / \u03bc",
    model: "Reference chord sets the length scale for Reynolds number. Comparing inertial transport with molecular viscosity at that scale characterizes the flow regime; this calculation does not predict transition or separation.",
    unit: "m",
  },
  "CLmax": {
    title: "Maximum lift coefficient \u2022 C<sub>L,MAX</sub>",
    desc: "Maximum lift coefficient used to calculate the 1-g stall speed.",
    eq: "V_S,TAS = \u221a(2 m g0 / (\u03c1 S_REF C_L,MAX))",
    model: "The limiting lift coefficient sets the lowest 1-g speed that can support the aircraft weight. Its value must come from aircraft data for the chosen flap configuration; the calculator does not predict it from geometry.",
    unit: "\u2014",
  },
  "NzPullup": {
    title: "Pull-up load factor \u2022 N<sub>Z</sub> (Pull-up)",
    desc: "Normal load factor for a pull-up maneuver. Bank angle is zero.",
    eq: "L = n m g0",
    model: "Normal load factor is lift divided by weight. The unbanked pull-up model increases lift demand without introducing the bank relation used for a level turn.",
    unit: "g",
  },
  "NzTurn": {
    title: "Level turn load factor \u2022 N<sub>Z</sub> (Turn)",
    desc: "Normal load factor in a coordinated level turn. Bank angle is derived from Nz = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "In a coordinated level turn, the vertical component of lift balances weight and the horizontal component provides centripetal acceleration. This gives n = 1/cos(bank), with bank magnitude below 90 degrees.",
    unit: "g",
  },
  "BankTurn": {
    title: "Level turn bank angle \u2022 \u03c6",
    desc: "Bank angle for a coordinated level turn. Load factor is derived from n = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "In a coordinated level turn, the vertical component of lift balances weight and the horizontal component provides centripetal acceleration. This gives n = 1/cos(bank), with bank magnitude below 90 degrees.",
    unit: "rad",
  },
  "Track": {
    title: "Ground track angle \u2022 χ",
    desc: "Track angle: direction of the ground-velocity vector.",
    eq: "\\vec{V}_{\\mathrm{ground}} = \\vec{V}_{\\mathrm{air}} + \\vec{V}_{\\mathrm{wind}}",
    model: "Track is the direction of the ground-velocity vector. Wind shifts it away from the air-relative direction through the horizontal wind triangle.",
    unit: "rad",
  },
  "Heading": {
    title: "Aircraft heading \u2022 ψ",
    desc: "Heading angle: direction the aircraft longitudinal axis points.",
    eq: "\\psi = \\text{aircraft heading}",
    model: "Heading describes the aircraft longitudinal axis. Sideslip relates that axis to the air-relative velocity, and wind then determines the ground track.",
    unit: "rad",
  },
  "Sideslip": {
    title: "Sideslip angle \u2022 β",
    desc: "Sideslip angle β: angle between the aircraft heading and the air-relative velocity direction.",
    eq: "\\beta = \\text{sideslip angle}",
    model: "Sideslip is the angular difference between the aircraft axis and its air-relative motion. The wind triangle uses it to orient the airspeed vector; it does not calculate side force or yaw dynamics.",
    unit: "rad",
  },
  "Drift": {
    title: "Drift angle \u2022 drift",
    desc: "Drift angle: heading minus track.",
    eq: "\\mathrm{drift} = \\psi - \\chi",
    model: "Drift is heading minus ground track. It combines the effects of wind and the selected sideslip rather than describing a force or an aerodynamic coefficient.",
    unit: "rad",
  },
  "HeadWind": {
    title: "Reference headwind \u2022 HW",
    desc: "Wind component along the selected runway/reference direction. Positive means headwind.",
    eq: "\\mathrm{HW} = V_W \\cos(\\psi_W - \\psi_{\\mathrm{RWY}})",
    model: "Projecting wind onto the selected runway axis gives the headwind component. A positive value opposes motion along that axis; a negative value is tailwind.",
    unit: "m/s",
  },
  "CrossWind": {
    title: "Reference crosswind \u2022 CW",
    desc: "Wind component perpendicular to the selected runway/reference direction.",
    eq: "\\mathrm{CW} = V_W \\sin(\\psi_W - \\psi_{\\mathrm{RWY}})",
    model: "Projecting wind onto the axis perpendicular to the runway gives the signed crosswind component. Together with headwind it reconstructs the horizontal wind vector.",
    unit: "m/s",
  },
  "Runway Angle": {
    title: "Runway reference angle \u2022 RWY",
    desc: "Reference direction used to resolve headwind and crosswind components.",
    eq: "\\psi_{\\mathrm{RWY}} = \\text{runway heading}",
    model: "The runway/reference direction defines the axes for headwind and crosswind. Rotating those axes changes the components without changing the physical wind vector.",
    unit: "rad",
  },
  "Aircraft Profile": {
    title: "Aircraft Profile • Geometry & Weights",
    desc: "Saved aircraft aerodynamic and mass configuration. Supplies the wing reference area, reference chord (MAC), operating masses, and flap C_L,MAX values.",
    eq: "L = q \\cdot S_{\\mathrm{REF}} \\cdot C_L",
    model: "A profile supplies reference geometry, masses, and flap lift limits to the aerodynamic equations. These are aircraft-data inputs; the calculator does not infer aircraft characteristics from its name.",
    unit: "m², m, kg",
  },
};
