// Auto-generated catalog from docs/quantity_catalog.json
export interface CatalogItem {
  title: string;
  desc: string;
  eq: string;
  model: string;
  unit: string;
}

export const CATALOG: Record<string, CatalogItem> = {
  "Pressure Altitude": {
    title: "Pressure altitude \u2022 Hp",
    desc: "Pressure altitude: altitude in the ISA atmosphere corresponding to the entered static pressure.",
    eq: "pISA(Hp) = p",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. See the documented geometric-altitude temperature convention.",
    unit: "m",
  },
  "Geometric Altitude": {
    title: "Geometric altitude \u2022 Hg",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "h = r H / (r \u2212 H)",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. See the documented geometric-altitude temperature convention.",
    unit: "m",
  },
  "Pressure": {
    title: "Static pressure \u2022 P",
    desc: "Static atmospheric pressure. AeroCalculator converts it to pressure altitude.",
    eq: "p = \u03c1 R T",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "Pa",
  },
  "Temperature": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Outside air temperature at the aircraft condition.",
    eq: "T = TISA(Hp) + \u0394T",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "K",
  },
  "Delta ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Temperature deviation from the ISA temperature at the current pressure altitude.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "K",
  },
  "True Airspeed": {
    title: "True airspeed \u2022 TAS",
    desc: "True Airspeed: aircraft speed relative to the surrounding air mass.",
    eq: "TAS = M a",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Calibrated Airspeed": {
    title: "Calibrated Airspeed \u2022 CAS",
    desc: "Indicated airspeed corrected for instrument and position errors. CAS is related to impact pressure using standard sea-level references.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Equivalent Airspeed": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Equivalent Airspeed: speed at standard sea-level density with the same dynamic pressure as the current flight condition.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Lift Coefficient CL": {
    title: "Lift coefficient \u2022 CL",
    desc: "Lift coefficient. With mass, load factor and reference area, it defines the required dynamic pressure.",
    eq: "CL = n m g0 / (q S)",
    model: "Available when dynamic pressure and reference area are positive. The sign follows the selected load factor.",
    unit: "\u2014",
  },
  "Dynamic Pressure": {
    title: "Dynamic pressure \u2022 Qdyn",
    desc: "Dynamic pressure q = \u00bd\u03c1V\u00b2.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "Pa",
  },
  "Impact Pressure": {
    title: "Impact pressure \u2022 Qc",
    desc: "Impact pressure qc = total pressure minus static pressure for the documented subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "Pa",
  },
  "Bank Angle \u03c6": {
    title: "Level turn bank angle \u2022 BankTurn",
    desc: "Bank angle for a coordinated level turn. Load factor is derived from Nz = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "Coordinated level turn: n \u2265 1 and |bank| < 90\u00b0.",
    unit: "rad",
  },
  "Track Angle": {
    title: "Ground track angle \u2022 Track",
    desc: "Track angle: direction of the ground-velocity vector.",
    eq: "Direction of Vground",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Heading Angle \u03a8": {
    title: "Aircraft heading \u2022 Heading",
    desc: "Heading angle: direction the aircraft longitudinal axis points.",
    eq: "Direction of the aircraft longitudinal axis",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Drift Angle": {
    title: "Drift angle \u2022 Drift",
    desc: "Drift angle: heading minus track.",
    eq: "drift = heading \u2212 track",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Sideslip Angle \u03b2": {
    title: "Sideslip angle \u2022 Sideslip",
    desc: "Sideslip angle \u03b2: angle between the aircraft heading and the air-relative velocity direction.",
    eq: "See documented wind convention",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Ground Speed": {
    title: "Ground speed \u2022 Ground Speed",
    desc: "Aircraft speed relative to the ground. Wind and direction inputs are used to recover the air-relative velocity.",
    eq: "Vground = Vair + Vwind",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Vs Factor": {
    title: "Stall speed factor \u2022 Vs Factor",
    desc: "Multiplier applied to the 1-g calibrated stall speed. The optional +\u0394 term is added in knots.",
    eq: "CAS = factor \u00d7 Vs,CAS + \u0394CAS",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "\u2014",
  },
  "Mach": {
    title: "Mach number \u2022 Mach",
    desc: "Mach number: True Airspeed divided by the local speed of sound.",
    eq: "M = TAS / a",
    model: "0 \u2264 M < 1 for the current compressibility model.",
    unit: "\u2014",
  },
  "Wind Speed": {
    title: "Wind speed \u2022 Wind Speed",
    desc: "Wind-vector magnitude. Use Wind Direction for its direction.",
    eq: "Vw = \u221a(HW\u00b2 + CW\u00b2)",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Wind Direction": {
    title: "Wind direction from \u2022 Wind Direction",
    desc: "Direction from which the wind is referenced in the wind-vector input mode.",
    eq: "Meteorological direction from",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Geopotencial Altitude": {
    title: "Geopotential altitude \u2022 H",
    desc: "Effective gravitational altitude used by the standard atmosphere.",
    eq: "H = r h / (r + h); for Hp/P input, H = Hp \u2212 29.271247 \u0394T ln(p/p0)",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. See the documented geometric-altitude temperature convention.",
    unit: "m",
  },
  "Density Altitude": {
    title: "Density altitude \u2022 H\u03c1",
    desc: "ISA altitude with the same density as the current condition.",
    eq: "\u03c1ISA(H\u03c1) = \u03c1",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m",
  },
  "Temperature Altitude": {
    title: "Temperature altitude \u2022 HT",
    desc: "Altitude returned by the documented temperature-altitude convention. Temperature alone is not a unique altitude across all layers.",
    eq: "TISA(HT) = T",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m",
  },
  "Density": {
    title: "Air density \u2022 \u03c1",
    desc: "Mass of air per unit volume.",
    eq: "\u03c1 = p / (R T)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "kg/m\u00b3",
  },
  "Total Temperature": {
    title: "Total temperature \u2022 Tt",
    desc: "Isentropic stagnation temperature for a calorically perfect gas.",
    eq: "Tt = T (1 + (\u03b3\u22121) M\u00b2/2)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "K",
  },
  "Viscosity": {
    title: "Dynamic viscosity \u2022 \u03bc",
    desc: "Dynamic viscosity from the documented temperature correlation.",
    eq: "Sutherland relation",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "Pa\u00b7s",
  },
  "Sound Speed": {
    title: "Speed of sound \u2022 a",
    desc: "Local speed of sound in the ideal-gas model.",
    eq: "a = \u221a(\u03b3 R T)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m/s",
  },
  "Stall Speed Vs": {
    title: "Reference stall speed \u2022 Vs",
    desc: "1-g reference stall speed displayed as CAS, independent of maneuver load factor.",
    eq: "Vs,TAS = \u221a(2 m g0 / (\u03c1 S CLmax)); displayed Vs,CAS = CAS(Vs,TAS)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m/s",
  },
  "Reynolds": {
    title: "Reynolds number \u2022 Re",
    desc: "Ratio of inertial and viscous effects based on reference chord.",
    eq: "Re = \u03c1 TAS cref / \u03bc",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "\u2014",
  },
  "Pressure Ratio \u03b4": {
    title: "Pressure ratio \u2022 \u03b4",
    desc: "Pressure divided by standard sea-level pressure.",
    eq: "\u03b4 = p / p0",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "\u2014",
  },
  "Density Ratio \u03c3": {
    title: "Density ratio \u2022 \u03c3",
    desc: "Density divided by standard sea-level density.",
    eq: "\u03c3 = \u03c1 / \u03c10",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "\u2014",
  },
  "Temperature Ratio \u03b8": {
    title: "Temperature ratio \u2022 \u03b8",
    desc: "Absolute temperature divided by standard sea-level temperature.",
    eq: "\u03b8 = T / T0",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "\u2014",
  },
  "Total Pressure": {
    title: "Total pressure \u2022 pt",
    desc: "Stagnation pressure from the subsonic isentropic relation.",
    eq: "pt = p + qc",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "Pa",
  },
  "DynPressure * S / g": {
    title: "Dynamic pressure force equivalent \u2022 qS/g0",
    desc: "Dynamic pressure times reference area, expressed as force in kgf.",
    eq: "q S / g0 (displayed as kgf)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "kgf",
  },
  "Lift Force": {
    title: "Lift force \u2022 L",
    desc: "Lift required by the selected mass and maneuver, displayed in kgf.",
    eq: "L / g0 = q S CL / g0 (displayed as kgf)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "kgf",
  },
  "Weight/Delta W/\u03b4": {
    title: "Weight divided by pressure ratio \u2022 W/\u03b4",
    desc: "Weight normalized by pressure ratio, displayed in kgf.",
    eq: "W / (\u03b4 g0) (displayed as kgf)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "kgf",
  },
  "Load Factor Nz": {
    title: "Normal load factor \u2022 n",
    desc: "Selected normal load factor. In a coordinated level turn, the load factor follows the selected bank angle or determines the bank angle.",
    eq: "n = 1 / cos \u03c6 (coordinated level turn)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "g",
  },
  "Turn Radius": {
    title: "Turn radius \u2022 r",
    desc: "Signed level-turn radius, unavailable at zero bank.",
    eq: "r = TAS\u00b2 / (g0 tan \u03c6)",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m",
  },
  "Turn Rate": {
    title: "Turn rate \u2022 \u03c9",
    desc: "Signed angular turn rate under the level-turn assumption.",
    eq: "\u03c9 = g0 tan \u03c6 / TAS",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "rad/s",
  },
  "AlongTrack Headwind": {
    title: "Along-track headwind \u2022 HW\u03c7",
    desc: "Positive headwind opposes travel along the calculated track.",
    eq: "Projection against ground track",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m/s",
  },
  "AlongTrack Crosswind": {
    title: "Along-track crosswind \u2022 CW\u03c7",
    desc: "Signed crosswind component in the documented convention.",
    eq: "Projection across ground track",
    model: "Within the documented model. Unavailable values are not plotted.",
    unit: "m/s",
  },
  "Hp": {
    title: "Pressure altitude \u2022 Hp",
    desc: "Pressure altitude: altitude in the ISA atmosphere corresponding to the entered static pressure.",
    eq: "pISA(Hp) = p",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. Geometric altitude is converted before the atmosphere calculation.",
    unit: "m",
  },
  "Hg": {
    title: "Geometric altitude \u2022 Hg",
    desc: "Geometric altitude: physical height above mean sea level.",
    eq: "H = r h / (r + h)",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. Geometric altitude is converted before the atmosphere calculation.",
    unit: "m",
  },
  "P": {
    title: "Static pressure \u2022 P",
    desc: "Static atmospheric pressure. AeroCalculator converts it to pressure altitude.",
    eq: "p = \u03c1 R T",
    model: "Pressure-altitude model: \u22125 to 84.852 km geopotential. Geometric altitude is converted before the atmosphere calculation.",
    unit: "Pa",
  },
  "\u0394 ISA": {
    title: "ISA temperature deviation \u2022 \u0394 ISA",
    desc: "Temperature deviation from the ISA temperature at the current pressure altitude.",
    eq: "\u0394T = T \u2212 TISA(Hp)",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "K",
  },
  "OAT": {
    title: "Outside air temperature \u2022 OAT",
    desc: "Outside air temperature at the aircraft condition.",
    eq: "T = TISA(Hp) + \u0394T",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "K",
  },
  "TAS": {
    title: "True airspeed \u2022 TAS",
    desc: "True Airspeed: aircraft speed relative to the surrounding air mass.",
    eq: "TAS = M a",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "CAS": {
    title: "Calibrated Airspeed \u2022 CAS",
    desc: "Indicated airspeed corrected for instrument and position errors. CAS is related to impact pressure using standard sea-level references.",
    eq: "CAS = a0 \u221a[2/(\u03b3\u22121) ((qc/p0 + 1)^((\u03b3\u22121)/\u03b3) \u2212 1)]",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "EAS": {
    title: "Equivalent airspeed \u2022 EAS",
    desc: "Equivalent Airspeed: speed at standard sea-level density with the same dynamic pressure as the current flight condition.",
    eq: "EAS = TAS \u221a(\u03c1/\u03c10)",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "CL": {
    title: "Lift coefficient \u2022 CL",
    desc: "Lift coefficient. With mass, load factor and reference area, it defines the required dynamic pressure.",
    eq: "CL = n m g0 / (q S)",
    model: "Positive value required for this calculation.",
    unit: "\u2014",
  },
  "Qdyn": {
    title: "Dynamic pressure \u2022 Qdyn",
    desc: "Dynamic pressure q = \u00bd\u03c1V\u00b2.",
    eq: "q = \u00bd \u03c1 TAS\u00b2",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "Pa",
  },
  "Qc": {
    title: "Impact pressure \u2022 Qc",
    desc: "Impact pressure qc = total pressure minus static pressure for the documented subsonic model.",
    eq: "qc = p [(1 + (\u03b3\u22121) M\u00b2/2)^(\u03b3/(\u03b3\u22121)) \u2212 1]",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "Pa",
  },
  "Weight": {
    title: "Aircraft mass \u2022 Weight",
    desc: "Aircraft mass used for lift, stall-speed and maneuver calculations.",
    eq: "W = m g0",
    model: "Positive value required for this calculation.",
    unit: "kg",
  },
  "Sref": {
    title: "Wing reference area \u2022 Sref",
    desc: "Wing reference area used in aerodynamic force and coefficient calculations.",
    eq: "L = q Sref CL",
    model: "Positive value required for this calculation.",
    unit: "m\u00b2",
  },
  "cref": {
    title: "Reference chord \u2022 cref",
    desc: "Wing reference chord used to calculate Reynolds number.",
    eq: "Re = \u03c1 TAS cref / \u03bc",
    model: "Positive value required for this calculation.",
    unit: "m",
  },
  "CLmax": {
    title: "Maximum lift coefficient \u2022 CLmax",
    desc: "Maximum lift coefficient used to calculate the 1-g stall speed.",
    eq: "Vs,TAS = \u221a(2 m g0 / (\u03c1 Sref CLmax))",
    model: "Positive value required for this calculation.",
    unit: "\u2014",
  },
  "NzPullup": {
    title: "Pull-up load factor \u2022 Nz (Pull-up)",
    desc: "Normal load factor for a pull-up maneuver. Bank angle is zero.",
    eq: "L = n m g0",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "g",
  },
  "NzTurn": {
    title: "Level turn load factor \u2022 Nz (Turn)",
    desc: "Normal load factor in a coordinated level turn. Bank angle is derived from Nz = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "Coordinated level turn: n \u2265 1 and |bank| < 90\u00b0.",
    unit: "g",
  },
  "BankTurn": {
    title: "Level turn bank angle \u2022 Bank (Turn)",
    desc: "Bank angle for a coordinated level turn. Load factor is derived from Nz = 1/cos(\u03c6).",
    eq: "n = 1 / cos \u03c6",
    model: "Coordinated level turn: n \u2265 1 and |bank| < 90\u00b0.",
    unit: "rad",
  },
  "Track": {
    title: "Ground track angle \u2022 Track",
    desc: "Track angle: direction of the ground-velocity vector.",
    eq: "Direction of Vground",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Heading": {
    title: "Aircraft heading \u2022 Heading",
    desc: "Heading angle: direction the aircraft longitudinal axis points.",
    eq: "Direction of the aircraft longitudinal axis",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Sideslip": {
    title: "Sideslip angle \u2022 Sideslip",
    desc: "Sideslip angle \u03b2: angle between the aircraft heading and the air-relative velocity direction.",
    eq: "See documented wind convention",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Drift": {
    title: "Drift angle \u2022 Drift",
    desc: "Drift angle: heading minus track.",
    eq: "drift = heading \u2212 track",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "HeadWind": {
    title: "Reference headwind \u2022 HeadWind",
    desc: "Wind component along the selected runway/reference direction. Positive means headwind.",
    eq: "Wind projection against reference",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "CrossWind": {
    title: "Reference crosswind \u2022 CrossWind",
    desc: "Wind component perpendicular to the selected runway/reference direction.",
    eq: "Wind projection across reference",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "m/s",
  },
  "Runway Angle": {
    title: "Runway reference angle \u2022 Runway Angle",
    desc: "Reference direction used to resolve headwind and crosswind components.",
    eq: "Reference for wind components",
    model: "Within the documented atmosphere and subsonic model. No aircraft operating limit is implied.",
    unit: "rad",
  },
  "Aircraft Profile": {
    title: "Aircraft Profile • Geometry & Weights",
    desc: "Saved aircraft aerodynamic and mass configuration. Supplies reference wing area Sref, mean aerodynamic chord cref, operating weights, and flap CLmax values.",
    eq: "L = q \\cdot S_{\\mathrm{ref}} \\cdot C_L",
    model: "Saved profiles are preserved in local storage and can be exported or imported.",
    unit: "m², m, kg",
  },
};
